# Generated by Django 4.2.20 on 2025-05-23 09:49

import common.Base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.CharField(default=common.Base.create_uuid, editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('del_state', models.IntegerField(choices=[(0, '已删除'), (1, '默认')], db_index=True, default=1, verbose_name='删除状态')),
                ('username', models.CharField(max_length=255)),
                ('iphone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'account_model',
            },
        ),
    ]
