# Generated by Django 4.2.20 on 2025-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_frontenduser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='backenduser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='超级用户'),
        ),
    ]
